name: Pull and Deploy workflow

on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Establish ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_URL }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd ~/webapps/portfolio
            git fetch origin
            git checkout main
            git pull
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r  ./dist/* /var/www/html
